### ISSUE TITLE
iMac G3 keyboard does not work after installation

### ISSUE THREAD

**Issue by GriffintheFolf** [kth5/archpower#60] opened 2023-07-30 19:05 UTC
I understand this issue has already been discussed in issue #52, but the symptoms are a bit different.

The keyboard works just fine from the install CD, but after booting an installed copy of Arch POWER from the hard drive, the keyboard is completely nonfunctional. Not even the caps lock light turns on when the key is pressed.

I have already tried (unsuccessfully) to figure out where the issue may be, but I cannot SSH into the system to view the kernel log, as dhcpcd does not seem to be started before the login prompt.

The iMac G3 in question is the Summer 2000 model with a 450 MHz G3, in case this information is needed.

**Comment by kth5** [comment] 2023-08-01 07:15
I've confirmed the problem on a G4 Powerbook as well. It seems as if it's not necessarily an issue with the kernel, if you are adventerous enough and install Xorg/Wayland from the installer with a graphical login-manager (say xdm) and enable it to autostart, the keyboard and mouse inputs work as expected. So evdev is good and input devices registered.

A bit baffled myself, I'll try to have a look at it but bit under time constraints lately.

**Comment by kth5** [comment] 2023-08-01 20:59
Identified where the problem is coming from and it's the `keymap` hook in `mkinitcpio`. Until this is fixed in a new point release of the `mkinitcpio` package or another, you can simply remote the hook in `/etc/mkinitcpio.conf` and re-generate your images via `mkinitcpio -p <your kernel>`.

**Comment by kth5** [comment] 2023-08-01 22:18
Brought it down to `loadkeys` which is part of `kbd`. Using `-b` it doesn't actually dump a binary that the `loadkmap` in the initramfs' `busybox` can load. Instead just the word `bkeymap`. Will see to fix this as soon as I can.

In the meantime, just disabling the `keymap` mkinitcpio hook is good enough and you'll get a US layout until systemd or your manual command sets something else later during the systems uptimes.

**Comment by kth5** [comment] 2023-08-01 22:33
`kbd-2.6.1-1.1` going to `testing` in a bit for `powerpc64` and `powerpc`.

**Comment by GriffintheFolf** [comment] 2023-08-01 23:26
I updated the system under the testing branch using the chroot from the live CD, and it works! I did still have to disable the "keymap" step from `mkinitcpio` however, otherwise none of the keys matched up with the characters they were supposed to be printing.

**Comment by kth5** [comment] 2023-08-02 07:28
Yep, I have the same effect on the PowerBook g4. It works better, as in actually generating a keymap.bin but one which doesn't quite work. Could be an endian issue.

**Comment by GriffintheFolf** [comment] 2023-08-02 16:23
When I tried to update the `kbd` package without disabling the keymap first, none of the keys matched up to what they should have; the right control key was B for example. So it probably is an endianness issue.

**Comment by kth5** [comment] 2023-08-04 21:18
`kbd-2.6.1-1.2` is in `testing`. Confirmed to properly work with `keymap` hook in unchanged mkinitcpio. Indeed, it was an endian issue in `kbd`.

https://github.com/kth5/archpower/blob/master/kbd/kbd-ppcbe-fix-loadkmap-compat.patch

**Comment by kth5** [comment] 2023-08-07 17:36
Confirmed on PowerMac G4/G5 with latest `testing` enabled.

**Closed by kth5** 2023-08-07 17:36 UTC
Labels: bug
