### ISSUE TITLE
[Installer] Empty /etc/resolve.conf file in ISO

### ISSUE THREAD

**Issue by Sadoon-AlBader** [kth5/archpower#2] opened 2019-05-19 14:58 UTC
I don't know if this is the right place, but the ISOs don't seem to have a DNS resolver, you could add openDNS or Google's DNS to the file using
nameserver x.x.x.x

I was having issues connecting to the internet in QEMU/KVM and this fixed it.

On a separate note, it seems the ISOs can't be booted directly on my POWER9 system, it just doesn't want to mount the root filesystem for some reason, so I am using QEMU/KVM to install Arch and then figure out what's wrong.

**Comment by kth5** [comment] 2019-05-24 07:34
The ISO should is getting the configuration via DHCP, I can confirm that it does not do so properly for the DNS.

Instead of imposing a DNS on anyone (8.8.8.8 isn't Google in China for instance) it should be fixed so that it requests the DNS properly from DNS.

What is your system by the way? A Talos II by any chance?

**Comment by Sadoon-AlBader** [comment] 2019-05-26 02:31
Yeah, my system is a Talos II Lite. I'll share screenshots of the broken boot process once I am free.

**Comment by kth5** [comment] 2019-05-26 09:04
That would be most helpful. 👍

**Comment by Sadoon-AlBader** [comment] 2019-06-22 16:45
Sorry for the late reply, life got a bit busy. Anyways here is the error.


```
SIGTERM received, booting...

[   33.512060] kexec_core: Starting new kernel

[    4.974512] IMC PMU (null) Register failed

Starting version 242.0-1-arch

[   15.919683] vio vio: uevent: failed to send synthetic uevent

[   15.954299] [drm:radeon_device_init [radeon]] *ERROR* Unable to find PCI I/O BAR

[   16.122970] [drm:radeon_atombios_init [radeon]] *ERROR* Unable to find PCI I/O BAR; using MMIO for ATOM IIO

[   16.134832] [drm:radeon_pm_init [radeon]] *ERROR* radeon: dpm initialization failed

mount: /run/archiso/bootmnt: no filesystem type specified.

ERROR; Failed to mount '/dev/disk/by-label/ARCH_201904'

   Falling back to interactive prompt

   You can try to fix the problem manually, log out when you are finished

sh: can't access tty; job control turned off

[rootfs ]# 
```


I got around this by installing using qemu on an Ubuntu install to the bare partition and it works flawlessly.
Also, I compiled quite a few useful packages and I have a minimal xfce4 desktop running. How can I upload packages to the repository? Also, we need a new repository for community and extra packages

**Comment by kth5** [comment] 2019-07-04 08:37
How exactly did you boot the ISO? Did you burn a copy or by other means?

I currently have no physical access to a Talos/Blackbird so I couldn't test booting on them yet.

**Comment by kth5** [comment] 2019-07-04 08:42
The latest ISO form today actually is the following:

https://archlinuxpower.org/iso/alpha/archlinux-2019.07.04-powerpc64le.iso

**Comment by Sadoon-AlBader** [comment] 2019-07-04 08:48
> How exactly did you boot the ISO? Did you burn a copy or by other means?
> 
> I currently have no physical access to a Talos/Blackbird so I couldn't test booting on them yet.

I didn't boot the ISO actually. I installed Ubuntu 19.04 and used QEMU to pacstrap to a physical partition. Once everything is where it should be, the built-in bootloader should recognize the Arch partition and boot normally. I can write up a full guide if you want.

**Comment by Sadoon-AlBader** [comment] 2019-07-04 08:49
> The latest ISO form today actually is the following:
> 
> https://archlinuxpower.org/iso/alpha/archlinux-2019.07.04-powerpc64le.iso

I'll try to boot from it and see if it works this time.

**Comment by kth5** [comment] 2019-07-04 08:50
> I didn't boot the ISO actually. I installed Ubuntu 19.04 and used QEMU to pacstrap to a physical partition. Once everything is where it should be, the built-in bootloader should recognize the Arch partition and boot normally. I can write up a full guide if you want.

I know about the DNS issue with DHCP when booting the ISO and am working on it. The question about the ISO came up since your log above indicates a problem much earlier than that.

**Comment by Sadoon-AlBader** [comment] 2019-07-04 09:11
> > I didn't boot the ISO actually. I installed Ubuntu 19.04 and used QEMU to pacstrap to a physical partition. Once everything is where it should be, the built-in bootloader should recognize the Arch partition and boot normally. I can write up a full guide if you want.
> 
> I know about the DNS issue with DHCP when booting the ISO and am working on it. The question about the ISO came up since your log above indicates a problem much earlier than that.
> 
> From what it looks like it can't find the volume with the label ARCH_201904 which can be anything like a thumb drive, cdrom or an actual partition for example. Could be a missing driver issue for your DVD/BD/CD drive or the like, which is why I'm asking so I can poke at something. :)

It was from a USB drive, I don't believe it can be a missing driver because once I pacstraped inside QEMU it booted baremetal just fine.

**Comment by kth5** [comment] 2019-07-04 10:02
> It was from a USB drive, I don't believe it can be a missing driver because once I pacstraped inside QEMU it booted baremetal just fine.

Booting an installed system with Qemu is quite diferent from booting the bare-metal from USB. The bootloader (petitboot in this case) will load the kernel and the ramdisk (archiso.img), the ramdisk has kernel modules and scripts to load the appropriate drivers and attempt to mount the labelled volume. Labeled so it doesn't matter if it's sda, vda or something entirely different.

It may simply not detect USB support or the like. On Qemu you're likely using the virtio or scsi emulation, which exposes non-removable storage devices only.

**Comment by kth5** [comment] 2019-09-04 11:11
Fixed in latest ISO:
https://archlinuxpower.org/iso/alpha/archlinux-2019.09.04-powerpc64le.iso

Simply migrated to dhclient, which seems to have no issue like dhcpcd (default on main Archlinux). It seems to have been an issue with dhcpcd interfacing with systemd-resolved, which I deemed an unnecessary step in this scenario.

**Closed** 2019-09-04 11:11 UTC
